name: oauth2_refresher
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/88888888oleg/oauth2_refresher

environment:
  sdk: ^3.5.4

dependencies:
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  dio: ^5.7.0



