name: oauth2_refresher
description: A Dart library for managing OAuth2 token refreshing with easy integration and support for Dio and JWT decoding.
version: 1.0.4
repository: https://github.com/88888888oleg/oauth2_refresher
homepage: https://dart-tools.dev

environment:
  sdk: ^3.5.4

dependencies:
  hive: ^2.2.3
  jwt_decoder: ^2.0.1
  dio: ^5.7.0



